altre modifiche

diff --git a/.azure/azure-pipeline.yaml b/.azure/azure-pipeline.yaml
--- a/.azure/azure-pipeline.yaml
+++ b/.azure/azure-pipeline.yaml
@@ -62,25 +62,52 @@ steps:
       done
     displayName: 'Start docker compose and wait for services'
 
+
 # Test API Frontend
   - script: |
-      curl --fail -X POST ${FRONTEND_URL} \
-      -H 'Content-Type: application/json' \
-      -d '$(TEST_DATA)'
+      RESPONSE=$(curl -s -o temp_front.json -w "%{http_code}" \
+        -X POST "$(FRONTEND_URL)" \
+        -H "Content-Type: application/json" \
+        -d '$(TEST_DATA)')
+
+      echo "HTTP Status: $RESPONSE"
+      echo "Response body:"
+      cat temp_front.json
+
+      if [ "$RESPONSE" = "201" ] && grep -q "submission successful" temp_front.json; then
+        echo "OK: Test frontend superato"
+      else
+        echo "FAIL: Test frontend fallito"
+        exit 1
+      fi
     displayName: 'Integration Test - Frontend API'
+
 
 # Test API Backend
   - script: |
-      curl 'http://localhost:8081/api/submission' \
-      -H 'Content-Type: application/json' \
-      --data-raw '{"name":"Andrea","surname":"Grossi","gender":"man","email":"xhunterx92@gmail.com","residencyCountry":"italy","fiscalCode":"GRNSRF92L31F205T","residencyZipCode":"20031","residencyAddress":"Via Enrico Berlinguer, 11","shipCountry":"italy","shipZipCode":"20031","shipAddress":"Via E.Berlingue, 11","privacy":true,"rules":true,"birthDate":"1992-07-31","phoneNumber":"3408461295","residencyProvince":"MI","shipProvince":"MI"}'
+      RESPONSE=$(curl -s -o temp.json -w "%{http_code}" \
+        -X POST "$(BACKEND_URL)" \
+        -H "Content-Type: application/json" \
+        -d '$(TEST_DATA)')
+
+      echo "HTTP Status: $RESPONSE"
+      echo "Response body:"
+      cat temp.json
+
+      if [ "$RESPONSE" = "201" ] && grep -q "submission successful" temp.json; then
+        echo "OK: Test backend superato"
+      else
+        echo "FAIL: Test backend fallito"
+        exit 1
+      fi
     displayName: 'Integration Test - Backend API'
+
 
 # Duplicate User Test (Negative Result)
   - script: |
-      curl -X POST ${FRONTEND_URL} \
+      curl -X POST "$(FRONTEND_URL)" \
       -H 'Content-Type: application/json' \
-      --data-raw "${TEST_DATA}"
+      --data-raw '$(TEST_DATA)'
     displayName: 'Integration Test - Frontend API (Negative)'
 
 # Test End to End with Playwright
@@ -88,7 +115,7 @@ steps:
 
 # Direct Database to verify created Users
   - script: |     
-      mysql -h localhost:3306 -u root -pmysecretpassword san_martino_friendship_day \
+      mysql -h localhost -u root -pmysecretpassword san_martino_friendship_day \
       -e "SELECT * FROM customers WHERE email='xhunterx92@gmail.com';"
     displayName: 'Verify Test User via MySQL Client' 
 
