switch order

diff --git a/.azure/azure-pipeline.yaml b/.azure/azure-pipeline.yaml
--- a/.azure/azure-pipeline.yaml
+++ b/.azure/azure-pipeline.yaml
@@ -18,18 +18,6 @@ steps:
       sudo apt-get install -y docker-compose
     displayName: 'Install docker compose'
 
-# Install MySQL client
-  - script: |
-      sudo apt-get update
-      sudo apt-get install -y mysql-client
-    displayName: 'Install MySQL Client'  
-
-# Install playwright
-  - script: |
-      npm install playwright
-      npx playwright install
-    displayName: 'Install Playwright'     
-
 # Build & Start Containers
   - script: |
       docker-compose down -v
@@ -62,6 +50,24 @@ steps:
       done
     displayName: 'Start docker compose and wait for services'
 
+# Test API Backend
+  - script: |
+      RESPONSE=$(curl -s -o temp.json -w "%{http_code}" \
+        -X POST "$(BACKEND_URL)" \
+        -H "Content-Type: application/json" \
+        -d '$(TEST_DATA)')
+
+      echo "HTTP Status: $RESPONSE"
+      echo "Response body:"
+      cat temp.json
+
+      if [ "$RESPONSE" = "201" ] && grep -q "submission successful" temp.json; then
+        echo "OK: Test backend superato"
+      else
+        echo "FAIL: Test backend fallito"
+        exit 1
+      fi
+    displayName: 'Integration Test - Backend API'
 
 # Test API Frontend
   - script: |
@@ -82,27 +88,6 @@ steps:
       fi
     displayName: 'Integration Test - Frontend API'
 
-
-# Test API Backend
-  - script: |
-      RESPONSE=$(curl -s -o temp.json -w "%{http_code}" \
-        -X POST "$(BACKEND_URL)" \
-        -H "Content-Type: application/json" \
-        -d '$(TEST_DATA)')
-
-      echo "HTTP Status: $RESPONSE"
-      echo "Response body:"
-      cat temp.json
-
-      if [ "$RESPONSE" = "201" ] && grep -q "submission successful" temp.json; then
-        echo "OK: Test backend superato"
-      else
-        echo "FAIL: Test backend fallito"
-        exit 1
-      fi
-    displayName: 'Integration Test - Backend API'
-
-
 # Duplicate User Test (Negative Result)
   - script: |
       curl -X POST "$(FRONTEND_URL)" \
@@ -110,14 +95,26 @@ steps:
       --data-raw '$(TEST_DATA)'
     displayName: 'Integration Test - Frontend API (Negative)'
 
-# Test End to End with Playwright
-
+# Install MySQL client
+  - script: |
+      sudo apt-get update
+      sudo apt-get install -y mysql-client
+    displayName: 'Install MySQL Client'  
 
 # Direct Database to verify created Users
   - script: |     
       mysql -h localhost -u root -pmysecretpassword san_martino_friendship_day \
       -e "SELECT * FROM customers WHERE email='xhunterx92@gmail.com';"
     displayName: 'Verify Test User via MySQL Client' 
+
+
+# Install playwright
+  - script: |
+      npm install playwright
+      npx playwright install
+    displayName: 'Install Playwright' 
+
+# Test End to End with Playwright
 
 # Stop and cleanup the Container
   - script: docker-compose down
